const BORROW_AND_SUPPLY_ABI = [
  {
    type: "constructor",
    stateMutability: "undefined",
    payable: false,
    inputs: [
      { type: "address", name: "_usdc" },
      { type: "address", name: "_oracle" },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "Accrued",
    inputs: [
      { type: "uint256", name: "newBorrowIndexE18", indexed: false },
      { type: "uint256", name: "newSupplyIndexE18", indexed: false },
      { type: "uint256", name: "totalBorrowsE6", indexed: false },
      { type: "uint256", name: "totalReservesE6", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "Borrowed",
    inputs: [
      { type: "address", name: "user", indexed: true },
      { type: "uint256", name: "amountE6", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "CollateralLocked",
    inputs: [
      { type: "address", name: "user", indexed: true },
      { type: "address", name: "asset", indexed: true },
      { type: "uint256", name: "qtyE6", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "CollateralUnlocked",
    inputs: [
      { type: "address", name: "user", indexed: true },
      { type: "address", name: "asset", indexed: true },
      { type: "uint256", name: "qtyE6", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "OracleSet",
    inputs: [{ type: "address", name: "oracle", indexed: false }],
  },
  {
    type: "event",
    anonymous: false,
    name: "OwnerTransferred",
    inputs: [{ type: "address", name: "newOwner", indexed: false }],
  },
  {
    type: "event",
    anonymous: false,
    name: "ParamsSet",
    inputs: [
      { type: "uint16", name: "ltvBps", indexed: false },
      { type: "uint16", name: "liqBps", indexed: false },
      { type: "uint16", name: "reserveBps", indexed: false },
      { type: "uint16", name: "baseBorrowBps", indexed: false },
      { type: "uint16", name: "slopeBorrowBps", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "Repaid",
    inputs: [
      { type: "address", name: "user", indexed: true },
      { type: "uint256", name: "amountE6", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "Supplied",
    inputs: [
      { type: "address", name: "user", indexed: true },
      { type: "uint256", name: "amountE6", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "Withdrawn",
    inputs: [
      { type: "address", name: "user", indexed: true },
      { type: "uint256", name: "amountE6", indexed: false },
    ],
  },
  {
    type: "function",
    name: "USDC",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "accountPortfolio",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "user" }],
    outputs: [
      { type: "uint256", name: "supplyE6" },
      { type: "uint256", name: "borrowE6" },
      { type: "uint256", name: "collateralValueE6" },
      { type: "uint256", name: "ltvCurrentBps" },
      { type: "uint256", name: "maxBorrowE6" },
    ],
  },
  {
    type: "function",
    name: "accrue",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "baseBorrowBps",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint16", name: "" }],
  },
  {
    type: "function",
    name: "borrow",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "amountE6" },
      { type: "address[]", name: "lockAssets" },
      { type: "uint256[]", name: "lockQtyE6" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "borrowIndexE18",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "borrowPrincipalE6",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "" }],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "borrowUserIndexE18",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "" }],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "collat",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [
      { type: "address", name: "" },
      { type: "address", name: "" },
    ],
    outputs: [
      { type: "uint128", name: "qtyE6" },
      { type: "bool", name: "listed" },
    ],
  },
  {
    type: "function",
    name: "collatList",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [
      { type: "address", name: "" },
      { type: "uint256", name: "" },
    ],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "currentBorrowAPR_BPS",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "currentSupplyAPR_BPS",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "htsAssociate",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "token" }],
    outputs: [],
  },
  {
    type: "function",
    name: "htsAssociateMany",
    constant: false,
    payable: false,
    inputs: [{ type: "address[]", name: "tokens" }],
    outputs: [],
  },
  {
    type: "function",
    name: "lastAccrual",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint64", name: "" }],
  },
  {
    type: "function",
    name: "lenderBalanceE6",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "user" }],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "liqBps",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint16", name: "" }],
  },
  {
    type: "function",
    name: "lockCollateral",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "asset" },
      { type: "uint256", name: "qtyE6" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "ltvBps",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint16", name: "" }],
  },
  {
    type: "function",
    name: "oracle",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "owner",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "repay",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "amountE6" }],
    outputs: [],
  },
  {
    type: "function",
    name: "reserveBps",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint16", name: "" }],
  },
  {
    type: "function",
    name: "setOracle",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "o" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setParams",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint16", name: "_ltvBps" },
      { type: "uint16", name: "_liqBps" },
      { type: "uint16", name: "_reserveBps" },
      { type: "uint16", name: "_baseBorrowBps" },
      { type: "uint16", name: "_slopeBorrowBps" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "slopeBorrowBps",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint16", name: "" }],
  },
  {
    type: "function",
    name: "supply",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "amountE6" }],
    outputs: [],
  },
  {
    type: "function",
    name: "supplyIndexE18",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "supplyPrincipalE6",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "" }],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "supplyUserIndexE18",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "" }],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "totalBorrowsE6",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "totalReservesE6",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "transferOwnership",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "n" }],
    outputs: [],
  },
  {
    type: "function",
    name: "unlockCollateral",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "asset" },
      { type: "uint256", name: "qtyE6" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "userCollaterals",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "user" }],
    outputs: [
      { type: "address[]", name: "assets" },
      { type: "uint256[]", name: "qtyE6" },
    ],
  },
  {
    type: "function",
    name: "utilization_BPS",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "withdraw",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "amountE6" }],
    outputs: [],
  },
];

export default BORROW_AND_SUPPLY_ABI;
