const CLOB_ABI = [
  {
    type: "constructor",
    stateMutability: "undefined",
    payable: false,
    inputs: [
      { type: "address", name: "_owner" },
      { type: "address", name: "_oracle" },
      { type: "address", name: "_adapter" },
      { type: "address", name: "_usdc" },
      { type: "address", name: "_feeSink" },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "AdapterSet",
    inputs: [{ type: "address", name: "adapter", indexed: false }],
  },
  {
    type: "event",
    anonymous: false,
    name: "Cancelled",
    inputs: [{ type: "uint256", name: "id", indexed: true }],
  },
  {
    type: "event",
    anonymous: false,
    name: "FeeBpsSet",
    inputs: [{ type: "uint16", name: "bps", indexed: false }],
  },
  {
    type: "event",
    anonymous: false,
    name: "FeeSinkSet",
    inputs: [{ type: "address", name: "sink", indexed: false }],
  },
  {
    type: "event",
    anonymous: false,
    name: "OracleSet",
    inputs: [{ type: "address", name: "oracle", indexed: false }],
  },
  {
    type: "event",
    anonymous: false,
    name: "OwnerTransferred",
    inputs: [{ type: "address", name: "newOwner", indexed: true }],
  },
  {
    type: "event",
    anonymous: false,
    name: "Placed",
    inputs: [
      { type: "uint256", name: "id", indexed: true },
      { type: "address", name: "asset", indexed: true },
      { type: "address", name: "trader", indexed: true },
      { type: "uint8", name: "side", indexed: false },
      { type: "bool", name: "isMarket", indexed: false },
      { type: "uint128", name: "qty", indexed: false },
      { type: "uint128", name: "pxE6", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "Trade",
    inputs: [
      { type: "address", name: "asset", indexed: true },
      { type: "uint256", name: "buyId", indexed: true },
      { type: "uint256", name: "sellId", indexed: true },
      { type: "address", name: "buyer", indexed: false },
      { type: "address", name: "seller", indexed: false },
      { type: "uint128", name: "qty", indexed: false },
      { type: "uint128", name: "pxE6", indexed: false },
      { type: "uint256", name: "notionalE6", indexed: false },
      { type: "uint256", name: "feeE6", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "VenueSet",
    inputs: [
      { type: "address", name: "asset", indexed: true },
      { type: "uint8", name: "state", indexed: false },
    ],
  },
  {
    type: "function",
    name: "USDC",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "adapter",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "asks",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [
      { type: "address", name: "" },
      { type: "uint256", name: "" },
    ],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "bandRange",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "asset" }],
    outputs: [
      { type: "uint256", name: "lo" },
      { type: "uint256", name: "hi" },
      { type: "uint64", name: "ts" },
    ],
  },
  {
    type: "function",
    name: "best",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "asset" }],
    outputs: [
      {
        type: "tuple",
        name: "bp",
        components: [
          { type: "uint128", name: "bidE6" },
          { type: "uint128", name: "askE6" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "bids",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [
      { type: "address", name: "" },
      { type: "uint256", name: "" },
    ],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "cancel",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "id" }],
    outputs: [],
  },
  {
    type: "function",
    name: "feeBps",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint16", name: "" }],
  },
  {
    type: "function",
    name: "feeSink",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "isFresh",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint64", name: "ts" }],
    outputs: [{ type: "bool", name: "" }],
  },
  {
    type: "function",
    name: "matchBest",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "asset" },
      { type: "uint256", name: "maxMatches" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "oracle",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "orders",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "" }],
    outputs: [
      { type: "address", name: "trader" },
      { type: "address", name: "asset" },
      { type: "uint8", name: "side" },
      { type: "bool", name: "isMarket" },
      { type: "uint128", name: "qty" },
      { type: "uint128", name: "pxE6" },
      { type: "uint64", name: "ts" },
      { type: "bool", name: "active" },
    ],
  },
  {
    type: "function",
    name: "ordersLength",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "owner",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "place",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "asset" },
      { type: "uint8", name: "side" },
      { type: "bool", name: "isMarket" },
      { type: "uint128", name: "qty" },
      { type: "uint128", name: "pxE6" },
    ],
    outputs: [{ type: "uint256", name: "id" }],
  },
  {
    type: "function",
    name: "setAdapter",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "a" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setFeeBps",
    constant: false,
    payable: false,
    inputs: [{ type: "uint16", name: "bps" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setFeeSink",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "sink" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setOracle",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "o" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setVenue",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "asset" },
      { type: "uint8", name: "state" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "transferOwnership",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "newOwner" }],
    outputs: [],
  },
  {
    type: "function",
    name: "venue",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "" }],
    outputs: [{ type: "uint8", name: "" }],
  },
];

export default CLOB_ABI;
